### ISSUE TITLE
become Compatible with home assistant 2022.8.0 bluethoot native support

### ISSUE THREAD

**Issue by romans3** [lolouk44/hassio-addons#62] opened 2022-07-28 15:52 UTC
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [ ] Xiaomi Mi Scale

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lolouk44** [comment] 2022-07-28 15:57
I'm not sure I understand what the issue is here.
Can you provide more details/references?

**Comment by romans3** [comment] 2022-07-28 16:17
After upgrade python to 10.3.5 in to homeassistant container this addon stop to work 😅

Can't get device info: No such device
Can't get device info: No such device
2022-07-28 18:10:24 - Bluetooth connection error: Failed to execute management command 'le on' (code: 17, error: Invalid Index)
2022-07-28 18:10:54 - Bluetooth connection error: Failed to execute management command 'le on' (code: 17, error: Invalid Index)
2022-07-28 18:11:24 - Bluetooth connection error: Failed to execute management command 'le on' (code: 17, error: Invalid Index)
2022-07-28 18:11:55 - Bluetooth connection error: Failed to execute management command 'le on' (code: 17, error: Invalid Index)
2022-07-28 18:12:25 - Bluetooth connection error: Failed to execute management command 'le on' (code: 17, error: Invalid Index)
2022-07-28 18:12:25 - 5+ Bluetooth connection errors. Resetting Bluetooth...
Can't get device info: No such device
Can't get device info: No such device

Breaking Changes

Below is a listing of the breaking change for this release, per subject or integration. Click on one of those to read more about the breaking change for that specific item

Bluetooth (multiple integrations)
Home Assistant is upgrading to Python 3.10 this release and comes with a breaking change affecting multiple integrations.

The integrations rely on the bluepy and pybluez libraries, which no longer work in newer versions of Python. bluepy has seen its last update in [December 2018](https://pypi.org/project/bluepy/#history) and hasn’t kept up with changes in the Python world. [Similar story](https://pypi.org/project/pybluez/#history) with pybluez.

We can’t mitigate this issue. If you are using one of these integrations, these will no longer work. We rather wanted to see a non-breaking solution, but we saw no backward compatible path or other solutions to aid this.

If you would like to help fix or upgrade one of these integrations, we would be grateful. We recommend migrating these integrations onto the [Bleak](https://pypi.org/project/bleak/) library instead.

([@pvizeli](https://github.com/pvizeli) - [#73830](https://github.com/home-assistant/core/pull/73830)) ([documentation](https://www.home-assistant.io/integrations/recorder/#configure-filter))

**Comment by lolouk44** [comment] 2022-07-28 17:26
Thanks. That sounds like a major refactor and I've just started a new job so not sure when I'll have time to do this...
I'll keep this issue open though until I fix it (if I can)

**Comment by diebobo** [comment] 2022-08-23 08:01
Would be great if you could fix it..Worked perfectly before HA broke it.. Hope you can fix it :)

**Comment by btehan** [comment] 2022-08-29 13:22
> Thanks. That sounds like a major refactor and I've just started a new job so not sure when I'll have time to do this... I'll keep this issue open though until I fix it (if I can)

Congratulations on the new job :-)

**Comment by lolouk44** [comment] 2022-09-10 00:35
Sorry for the delay, I've struggled to understand how to use the new bleak Bluetooh library.
I have however made a breakthrough today (well tonight it's 1.30 AM right now) and I have managed to get the basics to read weight and impedance from the scale!
I now need to rewrite most of the code to take into account the new library. There's also a very high chance that it will mean I won't be able to suppose the V1 scale anymore as I'm not getting the identifier sent through...

**Comment by diebobo** [comment] 2022-09-10 07:02
Good to hear you are actually putting effort into this, thanks a lot for that ! It's a pain when library's or dependency's change so dramaticly that your code is not only broken a bit but completely ruined.. 

I hope it will be working again without a zillion hours on it :)

**Comment by lolouk44** [comment] 2022-09-21 08:53
just posting an update, I have the code almost ready and working, except that it only works for ~2 days, then stops receiving bluetooth data. Still investigating...

**Comment by diebobo** [comment] 2022-09-23 08:23
Sounds good ! :) Almost there.

**Comment by lolouk44** [comment] 2022-09-29 21:41
I think I've cracked it. Changed the code again using a different function and it feels better already. Will give it a couple of days to ensure it stays alive and then can publish 😊

**Comment by lolouk44** [comment] 2022-10-02 12:37
Version [0.3.0](https://github.com/lolouk44/hassio-addons/releases/tag/0.3.0) has been pushed and is being built, you should see it popping up later today.
Hopefully there are no issues and you can start seeing data in HA again. Sorry it took so long

**Comment by diebobo** [comment] 2022-10-02 19:08
Thanks. got the update running :D.... Just wend on the scale but it didn't came through in Home Assistant. Gonna check what / why to morrow.. Thanks for now !!

**Comment by lolouk44** [comment] 2022-10-03 11:02
There are issues with the add-on specifically unfortunately (working fine on the stand-alone container).
Investigating...

**Comment by lolouk44** [comment] 2022-10-03 11:44
Following issues raised on https://github.com/lolouk44/hassio-addons/issues/63, I'll now close this thread as the request has been fulfulled (and the issue is being resolved with 0.3.2 which is being pushed to docker as we speak.
Thanks for your patience and understanding with the delays and issues ❤️

**Closed** 2022-10-03 11:44 UTC
Labels: enhancement

**Comment by robbinonline** [comment] 2022-11-09 12:18
Sorry to comment in this closed issue. But is for me it's not clear of this add-on works with the native Remote adapters support in Home Assistant? My server with HA and a bluetooth adapter is downstairs in the closet and my scale is upstairs.

**Comment by lolouk44** [comment] 2022-11-09 12:25
> Sorry to comment in this closed issue. But is for me it's not clear of this add-on works with the native Remote adapters support in Home Assistant? My server with HA and a bluetooth adapter is downstairs in the closet and my scale is upstairs.

Although I've not tested, I doubt it'll work as I have not built it with this in mind. I'm currently investigating the creation of a custom component that would simplify the setup ( no longer relying on MQTT as a middle man) and probably would mean it'd work with remote adapters (I take it you actually meant Bluetooth Proxy via an esphome device)

Unfortunately I have no ETA on this or if it'll even see the light of day as it's a massive undertaking to convert this and I have very limited knowledge of how to build HA components
