### ISSUE TITLE
No Data from Scale

### ISSUE THREAD

**Issue by mesut3000** [lolouk44/hassio-addons#69] opened 2022-10-11 16:33 UTC
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [ ] Xiaomi Mi Scale

**Describe the bug**
Hi,

Everything seems ok but I can not receive data from scale.

**To Reproduce**
Steps to reproduce the behaviour, including error message if any.

**Expected behaviour**

**Screenshots**

**Scale (please complete the following information):**
 - Name
 - Model # Xiaomi Mi Body Composition Scale 2

**Device running Home Assistant (please complete the following information):**
 - Raspberry Pi 4 4 GB
 - Two bluetooth devices, built on Rasperry and one external  USB Dongle Bluetooth device.

**Additional context**

Xiaomi Mi Scale
2022-10-11 07:37:33 - Loading Config From Add-On Options...
2022-10-11 07:37:33 - (INFO) -------------------------------------
2022-10-11 07:37:33 - (INFO) Starting Xiaomi mi Scale v0.3.6...
2022-10-11 07:37:33 - (INFO) Loading Config From Options.json...
2022-10-11 07:37:33 - (INFO) Logging Level Set to DEBUG...
2022-10-11 07:37:33 - (DEBUG) MISCALE_MAC read from config: 50:FB:19:38:11:CA
2022-10-11 07:37:33 - (DEBUG) MQTT_USERNAME read from config: mqtt
2022-10-11 07:37:33 - (DEBUG) MQTT_PASSWORD read from config: ***
2022-10-11 07:37:33 - (DEBUG) MQTT_HOST read from config: core-mosquitto
2022-10-11 07:37:33 - (DEBUG) MQTT_RETAIN read from config: True
2022-10-11 07:37:33 - (DEBUG) MQTT_PORT read from config: 1883
2022-10-11 07:37:33 - (DEBUG) MQTT_TLS_CACERTS read from config: Path to CA Cert File
2022-10-11 07:37:33 - (DEBUG) MQTT_TLS_INSECURE read from config: False
2022-10-11 07:37:33 - (DEBUG) MQTT_PREFIX read from config: miscale
2022-10-11 07:37:33 - (DEBUG) MQTT_DISCOVERY read from config: True
2022-10-11 07:37:33 - (DEBUG) MQTT_DISCOVERY_PREFIX read from config: homeassistant
2022-10-11 07:37:33 - (DEBUG) HCI_DEV read from config: hci0
2022-10-11 07:37:33 - (DEBUG) BLUEPY_PASSIVE_SCAN read from config: False
2022-10-11 07:37:33 - (INFO) Config Loaded...
2022-10-11 07:37:33 - (INFO) MQTT Discovery Setup Completed...
2022-10-11 07:37:33 - (INFO) -------------------------------------
2022-10-11 07:37:33 - (INFO) Initialization completed, step on scale to wake it up and get a weight value sent... Make sure the scale is within reach...
2022-10-11 07:37:33 - (DEBUG) Using selector: EpollSelector

**Comment by lolouk44** [comment] 2022-10-11 16:37
Please double check that you have the correct Mac address in your config. Also bring the scale close to your dongle / raspberry pi.

Please try with both hci0 (should be built in Bluetooth) and hci1 (should be bt dongle) and give me the logs

**Comment by mesut3000** [comment] 2022-10-11 17:12
> Please double check that you have the correct Mac address in your config. Also bring the scale close to your dongle / raspberry pi.
> 
> Please try with both hci0 (should be built in Bluetooth) and hci1 (should be bt dongle) and give me the logs

Hi,

Tried hci0 and hci1 many times, nothing changed. Mac adress is also correct, doublechecked. Also tried "BLUEPY_PASSIVE_SCAN"  true or false.

Scale is very close, only 1 meter away from Raspberry Pi. My scale is also working with "Bluetooth Low Energy Monitor / Passive BLE monitor" integration. There is no issue there, I can track my weight instantly.

My mac address :
![copy Screenshot_20221011-194912](https://user-images.githubusercontent.com/68826444/195154319-3f60b7c6-3aab-444c-89b6-7f36ec39223c.png)

My Configuration:

HCI_DEV: hci0
BLUEPY_PASSIVE_SCAN: false
MISCALE_MAC: 50:FB:19:38:11:CA
MQTT_PREFIX: miscale
MQTT_HOST: core-mosquitto
MQTT_USERNAME: mqtt
MQTT_PASSWORD: xxx
MQTT_PORT: 1883
MQTT_RETAIN: true
MQTT_DISCOVERY: true
MQTT_DISCOVERY_PREFIX: homeassistant
MQTT_TLS_CACERTS: Path to CA Cert File
MQTT_TLS_INSECURE: false
DEBUG_LEVEL: DEBUG
USERS:
  - NAME: XX
    SEX: male
    GT: 60
    LT: 64
    HEIGHT: 168
    DOB: "XXX"
  - NAME: XX
    SEX: female
    GT: 55
    LT: 60
    HEIGHT: 160
    DOB: "XXX"
  - NAME: XX
    SEX: male
    GT: 14
    LT: 30
    HEIGHT: 101
    DOB: "XXX"

Configuration YAML setting :

mqtt:
  sensor:
    - name: "My Weight"
      state_topic: "miscale/Mesut/weight"
      value_template: "{{ value_json['weight'] }}"
      unit_of_measurement: "kg"
      json_attributes_topic: "miscale/Mesut/weight"
      icon: mdi:scale-bathroom
      # Below lines only needed if long term statistics are required
      state_class: "measurement"

It was working fine before 2022.10 release I think.

**Comment by mesut3000** [comment] 2022-10-11 17:50
I solved this situation finally, I think it was because a hardware lag.

A few minutes ago I turned off my Raspberry Pi's power and a few seconds later I turn on. And voila, I saw my scale found in the logs.

I restarted my Home Assistant many times, updated system and addon many times, nothing changed for a few day. I can't believe I found a solution like this.

And here is my final log :

(Issue can be closed now, it is good to be back again :)
.............
.............
2022-10-11 20:35:31 - (DEBUG) Using selector: EpollSelector
2022-10-11 20:35:46 - (DEBUG) miscale found, with advertising_data: AdvertisementData(local_name='MIBFS', manufacturer_data={343: b'P\xfb\x198\x11\xca'}, service_data={'0000181b-0000-1000-8000-00805f9b34fb': b'\x02\x84\xb2\x07\x01\x03\n\x15\x14\x00\x00x\x05'}, service_uuids=['0000181b-0000-1000-8000-00805f9b34fb'])
2022-10-11 20:35:46 - (DEBUG) miscale v2 found (service data: 0000181b-0000-1000-8000-00805f9b34fb)
2022-10-11 20:40:05 - (DEBUG) miscale found, with advertising_data: AdvertisementData(local_name='MIBFS', manufacturer_data={343: b'P\xfb\x198\x11\xca'}, service_data={'0000181b-0000-1000-8000-00805f9b34fb': b'\x02\xa6\xb2\x07\x01\x03\n)6\xcd\x01~1'}, service_uuids=['0000181b-0000-1000-8000-00805f9b34fb'])
2022-10-11 20:40:05 - (DEBUG) miscale v2 found (service data: 0000181b-0000-1000-8000-00805f9b34fb)
2022-10-11 20:40:05 - (INFO) Publishing data to topic miscale/Mesut/weight:  
...........
............

**Comment by lolouk44** [comment] 2022-10-11 18:11
Glad to know it's working. Feel free to close this issue

**Comment by mesut3000** [comment] 2022-10-18 20:22
There is something wrong with integration or maybe an issue hardware related,not sure.
If I restart HA, integration mi scale is not working. Also there is no sign in the log. If I turn off and then turn on raspberry Pi power directly, mi scale appears in the log and it works. If I restart from HA, it disappears.Strange

**Comment by lolouk44** [comment] 2022-10-19 09:29
No idea how to tackle this one. If restarting the Pi makes it work, maybe you have an issue with the bluetooth radio.
Can you try this and see if it works:
1. switch HA off
2. restart your bluetooth radio
3. restart HA
This might make it work. if so I'll see if I can add something to handle when the add-on gets killed, could be that resources are not correctly released by HA...

**Comment by reaper7** [comment] 2022-10-19 13:41
in my case, the weight is read only once (after power off/on cycle), restarting only ha does not improve the situation.
I tried to remove bluetooth integration from ha, also no improvement.

**Comment by lolouk44** [comment] 2022-10-19 19:32
> in my case, the weight is read only once (after power off/on cycle), restarting only ha does not improve the situation.
> I tried to remove bluetooth integration from ha, also no improvement.

Can you set your logs to debug and provide the logs please?

**Comment by reaper7** [comment] 2022-10-20 06:35
I do not have access to the logs at the moment
but the initialization log looks like in the first post, logs when reading as in post 4, no more information appears after that.
There is nothing disturbing about the logs.

Yesterday I restarted the bluetooth service on the host machine (without power off/on) but I forgot to check the scale readings
and after a few hours I remembered to check the weight -> readings popped up!
but it's not working again this morning.

I have yet to confirm it,
it seems that no matter how long it takes from restarting the host or the bluetooth service itself, the reading will be possible only during the first weighing, then everything "freezes".

**Comment by laurentmahe** [comment] 2022-10-24 15:23
@mesut3000 @reaper7 I need some logs in debug mode pls

**Comment by lolouk44** [comment] 2022-10-24 15:26
@mesut3000 @reaper7 I need some logs in debug mode pls

**Comment by reaper7** [comment] 2022-10-24 19:25
@lolouk44 - probably my problem is not caused by your add-on.
In the meantime I replaced the HA built-in eq3-bt thermostat component with custom which correctly recognizes the thermostats and just works. At the same time, problems with reading the weight have disappeared.
...so probably the original thermostat component was causing general bluetooth problems.

**Comment by lolouk44** [comment] 2022-10-24 23:15
@mesut3000 do you have any other Bluetooth integrations on?

**Comment by mesut3000** [comment] 2022-10-25 09:17
> @mesut3000 do you have any other Bluetooth integrations on?

Hi, sorry for late response. Yes I have Bluetooth Low Energy Monitor, Passive BLE integration. 5 devices, xiaomi humidity and temperature sensors. Also my scale is added here and it is working without an issue. I also tried hci0 and hci1, nothing changed.

**Comment by mesut3000** [comment] 2022-10-25 09:21
My debug log:
2022-10-25 12:10:18 - Loading Config From Add-On Options...
2022-10-25 12:10:18 - (INFO) -------------------------------------
2022-10-25 12:10:18 - (INFO) Starting Xiaomi mi Scale v0.3.6...
2022-10-25 12:10:18 - (INFO) Loading Config From Options.json...
2022-10-25 12:10:18 - (INFO) Logging Level Set to DEBUG...
2022-10-25 12:10:18 - (DEBUG) MISCALE_MAC read from config: 50:FB:19:38:11:CA
2022-10-25 12:10:18 - (DEBUG) MQTT_USERNAME read from config: mqtt
2022-10-25 12:10:18 - (DEBUG) MQTT_PASSWORD read from config: ***
2022-10-25 12:10:18 - (DEBUG) MQTT_HOST read from config: core-mosquitto
2022-10-25 12:10:18 - (DEBUG) MQTT_RETAIN read from config: True
2022-10-25 12:10:18 - (DEBUG) MQTT_PORT read from config: 1883
2022-10-25 12:10:18 - (DEBUG) MQTT_TLS_CACERTS read from config: Path to CA Cert File
2022-10-25 12:10:18 - (DEBUG) MQTT_TLS_INSECURE read from config: False
2022-10-25 12:10:18 - (DEBUG) MQTT_PREFIX read from config: miscale
2022-10-25 12:10:18 - (DEBUG) MQTT_DISCOVERY read from config: True
2022-10-25 12:10:18 - (DEBUG) MQTT_DISCOVERY_PREFIX read from config: homeassistant
2022-10-25 12:10:18 - (DEBUG) HCI_DEV read from config: hci1
2022-10-25 12:10:18 - (DEBUG) BLUEPY_PASSIVE_SCAN read from config: False
2022-10-25 12:10:18 - (INFO) Config Loaded...
2022-10-25 12:10:18 - (INFO) MQTT Discovery Setup Completed...
2022-10-25 12:10:18 - (INFO) -------------------------------------
2022-10-25 12:10:18 - (INFO) Initialization completed, step on scale to wake it up and get a weight value sent... Make sure the scale is within reach...
2022-10-25 12:10:18 - (DEBUG) Using selector: EpollSelector

**Comment by lolouk44** [comment] 2022-10-25 10:19
> Also my scale is added here and it is working without an issue

so it's working and this issue can be closed?

**Comment by mesut3000** [comment] 2022-10-25 10:25
No, it is working under Bluetooth Low Energy Monitor integration, but not working with addon, so i can not track my logs.

Difference between logs :


If I shut down my power of Raspberry Pi and start :

2022-10-11 20:35:31 - (DEBUG) Using selector: EpollSelector
2022-10-11 20:35:46 - (DEBUG) miscale found, with advertising_data: AdvertisementData(local_name='MIBFS', manufacturer_data={343: b'P\xfb\x198\x11\xca'}, service_data={'0000181b-0000-1000-8000-00805f9b34fb': b'\x02\x84\xb2\x07\x01\x03\n\x15\x14\x00\x00x\x05'}, service_uuids=['0000181b-0000-1000-8000-00805f9b34fb'])
2022-10-11 20:35:46 - (DEBUG) miscale v2 found (service data: 0000181b-0000-1000-8000-00805f9b34fb)
2022-10-11 20:40:05 - (DEBUG) miscale found, with advertising_data: AdvertisementData(local_name='MIBFS', manufacturer_data={343: b'P\xfb\x198\x11\xca'}, service_data={'0000181b-0000-1000-8000-00805f9b34fb': b'\x02\xa6\xb2\x07\x01\x03\n)6\xcd\x01~1'}, service_uuids=['0000181b-0000-1000-8000-00805f9b34fb'])
2022-10-11 20:40:05 - (DEBUG) miscale v2 found (service data: 0000181b-0000-1000-8000-00805f9b34fb)
2022-10-11 20:40:05 - (INFO) Publishing data to topic miscale/Mesut/weight:
...........

miScale is found.


But if I restart Home Assistant from software :

2022-10-25 12:10:18 - (INFO) MQTT Discovery Setup Completed...
2022-10-25 12:10:18 - (INFO) -------------------------------------
2022-10-25 12:10:18 - (INFO) Initialization completed, step on scale to wake it up and get a weight value sent... Make sure the scale is within reach...
2022-10-25 12:10:18 - (DEBUG) Using selector: EpollSelector

...
No sign of miScale

**Comment by mesut3000** [comment] 2022-10-25 10:51
My core log :

![image](https://user-images.githubusercontent.com/68826444/197754576-75f3cb6b-d265-4b91-966c-abb58372a825.png)

**Comment by lolouk44** [comment] 2022-10-25 11:07
It souunds like there may be some incompatibility with other bluetooth integrations as experienced by reaper7.
What if you turn off all your other bluetooth integrations, are you then able to restart HA and see data from the scale?

**Comment by mesut3000** [comment] 2022-10-25 11:20
Also disabled integrations; nothing changed :

![image](https://user-images.githubusercontent.com/68826444/197759626-a172a4b0-959d-4ae5-8ad9-2890429a2611.png)

**Comment by lolouk44** [comment] 2022-10-25 11:27
There's something funky with your setup. I have no idea why it's not working for you.
I'm sorry it's not something I can help with as I'm not getting anything to help me investigate and clealy it works after a Pi restart.
I'm going to close this issue now. However if you find more information to help me fix it, feel free to reopen and share the info.

**Closed by lolouk44** 2022-10-25 11:27 UTC
Labels: bug
