### ISSUE TITLE
[FATAL tini (7)] exec /entrypoint.sh failed: Permission denied

### ISSUE THREAD

**Issue by kamilsulek** [lolouk44/hassio-addons#24] opened 2020-11-24 14:14 UTC
After update new version 0.1.13 on HASSIO addon not working. I have message in log:

[FATAL tini (7)] exec /entrypoint.sh failed: Permission denied

I don't use docker.

**Comment by lolouk44** [comment] 2020-11-24 14:55
Hi @kamilsulek 
Duplicate of https://github.com/lolouk44/hassio-addons/issues/23
Fixed in 0.1.14

**Closed by lolouk44** 2020-11-24 14:55 UTC
Labels: bug
